import numpy as np
import librosa
from training.src.dataset_autoencoder import prepare_mimii_data

GAIN_CORRECTION = 2.419084 # CHANGE IN ACCORDANCE TO compute_gain_ratio.py

# Re-run to recover the normalization constants
_, _, _, _, global_mean, global_std = prepare_mimii_data("data/fan", gain_correction=GAIN_CORRECTION)

# Save for future use
np.save("training/global_mean.npy", global_mean)
np.save("training/global_std.npy", global_std)

mean_scalar = float(global_mean.squeeze())
std_scalar  = float(global_std.squeeze())

print(f"kGlobalMean = {mean_scalar:.6f}")
print(f"kGlobalStd  = {std_scalar:.6f}")

sr    = 16000
n_fft = 1024
mel_fb = librosa.filters.mel(sr=sr, n_fft=n_fft, n_mels=104)

with open("deployment/anomaly_detector_autoencoder/mel_filters.h", "w") as f:
    f.write("#pragma once\n\n")
    f.write("// Auto-generated by export_arduino_constants.py -- do not edit\n\n")
    f.write("const float kMelFilters[104][513] PROGMEM = {\n")
    for row in mel_fb:
        vals = ", ".join(f"{v:.6f}f" for v in row)
        f.write(f"  {{{vals}}},\n")
    f.write("};\n\n")
    f.write(f"constexpr float kGlobalMean = {mean_scalar:.6f}f;\n")
    f.write(f"constexpr float kGlobalStd  = {std_scalar:.6f}f;\n")

# diagnostic
audio, sr2 = librosa.load("data/fan/id_00/normal/00000000.wav", sr=16000)
window = audio[:16000]

mel = librosa.feature.melspectrogram(
    y=window, sr=sr2, n_mels=104, n_fft=1024, hop_length=1000, power=2.0
)
log_mel = librosa.power_to_db(mel, ref=np.max)  # (104, 16)

print("\nlog_mel shape:", log_mel.shape)
print("frameMax:", log_mel.max())
print("Pre-norm mel[0..7] frame 0:", log_mel[:8, 0])

normalized = (log_mel - global_mean.squeeze()) / global_std.squeeze()
print("Post-norm feat[0..7] frame 0:", normalized[:8, 0])

