#include <PDM.h>
#include <arduinoFFT.h>
#include <TensorFlowLite.h>
#include <tensorflow/lite/micro/all_ops_resolver.h>
#include <tensorflow/lite/micro/micro_interpreter.h>
#include <tensorflow/lite/schema/schema_generated.h>
#include "model_data.h"
#include "mel_filters.h"   // <-- generated by the Python snippet

constexpr int SAMPLE_RATE = 16000;
constexpr int N_FFT = 1024;
constexpr int HOP_LENGTH = 1000;
constexpr int N_MELS_FULL = 104;
constexpr int NUM_FRAMES = 16;
constexpr int FEATURE_SIZE = N_MELS_FULL * NUM_FRAMES; // 104*16=1664

// Threshold written by evaluate_autoencoder.py
constexpr float kAnomalyThreshold = 0.049993f;

constexpr float kAlpha = 0.3f;
float smoothed_mse = 0.0f;

// N_FFT/2+1 = 513 bins
double vReal[N_FFT];
double vImag[N_FFT];

float featureBuffer[FEATURE_SIZE];  // z-score normalized, matches model input

ArduinoFFT<double> FFT(vReal, vImag, N_FFT, SAMPLE_RATE);

constexpr int kTensorArenaSize = 40 * 1024;
uint8_t tensor_arena[kTensorArenaSize];

tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor* input  = nullptr;
TfLiteTensor* output = nullptr;

// Replace the samplesRead volatile int + sampleBuffer with these:
constexpr int PDM_BUFFER_SIZE = 256;
short pdmBuffer[PDM_BUFFER_SIZE];
volatile int pdmSamplesReady = 0;

short captureBuffer[N_FFT];   // accumulates until we have N_FFT samples
int   captureIndex = 0;

void onPDMdata()
{
    int bytes = PDM.available();
    if (bytes > (int)sizeof(pdmBuffer))
        bytes = sizeof(pdmBuffer);
    PDM.read(pdmBuffer, bytes);
    pdmSamplesReady = bytes / sizeof(short);
}

void setup()
{
    Serial.begin(115200);
    while (!Serial) delay(10);

    Serial.println("=== TinyML Autoencoder Boot ===");
    pinMode(LED_BUILTIN, OUTPUT);
    digitalWrite(LED_BUILTIN, LOW);

    PDM.onReceive(onPDMdata);
    PDM.setGain(40);
    if (!PDM.begin(1, SAMPLE_RATE))
    {
        Serial.println("ERROR: PDM.begin failed");
        while (1);
    }

    // Discard first 50 callbacks to let PDM AGC stabilize
    int warmupCount = 0;
    while (warmupCount < 50) {
        if (pdmSamplesReady > 0) {
            pdmSamplesReady = 0;
            warmupCount++;
        }
        delay(1);
    }
    Serial.println("PDM warmed up");

    const tflite::Model* model = tflite::GetModel(g_model_data);
    if (model->version() != TFLITE_SCHEMA_VERSION)
    {
        Serial.println("ERROR: Schema mismatch");
        while (1);
    }

    static tflite::AllOpsResolver resolver;
    static tflite::MicroInterpreter static_interpreter(
        model, resolver, tensor_arena, kTensorArenaSize);
    interpreter = &static_interpreter;

    if (interpreter->AllocateTensors() != kTfLiteOk)
    {
        Serial.println("ERROR: AllocateTensors failed");
        while (1);
    }

    input  = interpreter->input(0);
    output = interpreter->output(0);
    Serial.println("Setup complete");
}

void loop()
{
    Serial.println("--- loop start ---");
    Serial.print("kGlobalMean = ");
    Serial.println(kGlobalMean, 8);

    // collect mel power (linear, pre-log) for all frames
    float melPower[N_MELS_FULL][NUM_FRAMES];
    float globalMaxPower = 1e-10f;

    for (int frame = 0; frame < NUM_FRAMES; frame++)
    {
        // Accumulate N_FFT samples from successive PDM callbacks
        captureIndex = 0;
        while (captureIndex < N_FFT)
        {
            if (pdmSamplesReady > 0)
            {
                noInterrupts();
                int toCopy = min(pdmSamplesReady, N_FFT - captureIndex);
                memcpy(&captureBuffer[captureIndex], pdmBuffer, toCopy * sizeof(short));
                int ready = pdmSamplesReady;
                pdmSamplesReady = 0;
                interrupts();
                captureIndex += toCopy;
            }
        }
        if (frame == 0) {
            float pcmMax = 0;
            for (int i = 0; i < N_FFT; i++)
                pcmMax = max(pcmMax, (float)abs(captureBuffer[i]));
            Serial.print("PCM max frame 0: ");
            Serial.println(pcmMax);
        }

        memset(vReal, 0, sizeof(vReal));
        memset(vImag, 0, sizeof(vImag));
        for (int i = 0; i < N_FFT; i++)
            vReal[i] = (double)captureBuffer[i];

        FFT.windowing(FFT_WIN_TYP_HANN, FFT_FORWARD);
        FFT.compute(FFT_FORWARD);
        FFT.complexToMagnitude();

        for (int k = 0; k < 513; k++) {
            float mag = (float)vReal[k];
            vReal[k] = mag * mag;
        }

        // Apply mel filterbank → linear power per band
        for (int m = 0; m < N_MELS_FULL; m++)
        {
            float energy = 0.0f;
            for (int k = 0; k < 513; k++)
            {
                float filterVal = pgm_read_float(&kMelFilters[m][k]);
                energy += filterVal * (float)vReal[k];  // vReal already holds power
            }
            melPower[m][frame] = energy;  // no squaring — energy is already power
            if (melPower[m][frame] > globalMaxPower)
                globalMaxPower = melPower[m][frame];
        }
    }

    Serial.print("globalMaxPower: ");
    Serial.println(globalMaxPower, 6);

    // power_to_db with ref=max — divide in power domain THEN log
    float melFrames[N_MELS_FULL][NUM_FRAMES];
    for (int m = 0; m < N_MELS_FULL; m++)
        for (int f = 0; f < NUM_FRAMES; f++)
            melFrames[m][f] = 10.0f * log10f((melPower[m][f] / (globalMaxPower + 1e-9f)) + 1e-10f);

    Serial.print("Post-dB mel[0..7] frame 0: ");
    for (int m = 0; m < 8; m++) {
        Serial.print(melFrames[m][0], 4);
        Serial.print(' ');
    }
    Serial.println();

    // z-score normalize + quantize into input tensor
    for (int m = 0; m < N_MELS_FULL; m++)
    {
        for (int f = 0; f < NUM_FRAMES; f++)
        {
            int idx = m * NUM_FRAMES + f;
            float normalized = (melFrames[m][f] - kGlobalMean) / kGlobalStd;
            featureBuffer[idx] = normalized;

            int32_t quantized = (int32_t)roundf(
                normalized / input->params.scale + input->params.zero_point);
            quantized = constrain(quantized, -128, 127);
            input->data.int8[idx] = (int8_t)quantized;
        }
    }

    float featMin = 1e10f, featMax = -1e10f, featSum = 0.0f;
    int inRange = 0;
    for (int i = 0; i < FEATURE_SIZE; i++) {
        featMin = min(featMin, featureBuffer[i]);
        featMax = max(featMax, featureBuffer[i]);
        featSum += featureBuffer[i];
        if (featureBuffer[i] > -2.0f && featureBuffer[i] < 2.0f) inRange++;
    }
    Serial.print("Feat min/max/mean: ");
    Serial.print(featMin, 3); Serial.print(" / ");
    Serial.print(featMax, 3); Serial.print(" / ");
    Serial.println(featSum / FEATURE_SIZE, 3);
    Serial.print("% in [-2,2]: ");
    Serial.println(100.0f * inRange / FEATURE_SIZE, 1);

    Serial.print("Post-norm feat[0..7]: ");
    for (int i = 0; i < 8; i++) {
        Serial.print(featureBuffer[i], 4);
        Serial.print(' ');
    }
    Serial.println();

    // Inference
    if (interpreter->Invoke() != kTfLiteOk)
    {
        Serial.println("Inference failed");
        delay(1000);
        return;
    }

    // MSE: featureBuffer (original float) vs dequantized output
    float total_mse = 0.0f;
    for (int i = 0; i < FEATURE_SIZE; i++)
    {
        float out_val = ((float)output->data.int8[i] - output->params.zero_point)
                        * output->params.scale;
        float err = featureBuffer[i] - out_val;
        total_mse += err * err;
    }
    float mse = total_mse / (float)FEATURE_SIZE;

    //// This section is a hardcoded patch; it seemed like values were just getting
    //// linearly shifted by about 2.6 up.
    smoothed_mse = (kAlpha * mse) + ((1.0f - kAlpha) * smoothed_mse);
    // Known bounds based on observations
    constexpr float kObservedMin = 0.3f;
    constexpr float kObservedMax = 1.8f;

    // Linearly map [2.6, 3.4] to [0.0, 1.0]
    float normalized_score = (smoothed_mse - kObservedMin) / (kObservedMax - kObservedMin);

    // Constrain to ensure we don't get values outside [0, 1] due to spikes
    normalized_score = constrain(normalized_score, 0.0f, 1.0f);

    bool is_anomaly = (normalized_score > 0.3);
    // bool is_anomaly = (smoothed_mse > kAnomalyThreshold);

    Serial.print("Score: ");       Serial.print(mse, 6);
    Serial.print(" | Smoothed: "); Serial.print(smoothed_mse, 6);
    Serial.print(" | Threshold: "); Serial.print(kAnomalyThreshold, 6);
    Serial.print(" | Normalized Score: "); Serial.print(normalized_score, 6);
    Serial.print(" | Anomaly: ");  Serial.println(is_anomaly ? "YES" : "NO");

    digitalWrite(LED_BUILTIN, is_anomaly ? HIGH : LOW);
    delay(500);
}

// This loop is to compute gain, captures one second of audio
// void loop() {
//     static bool done = false;
//     if (done) return;
    
//     // Collect 16000 samples
//     static short recordBuffer[16000];
//     int recorded = 0;
    
//     while (recorded < 16000) {
//         if (pdmSamplesReady > 0) {
//             noInterrupts();
//             int toCopy = min(pdmSamplesReady, 16000 - recorded);
//             memcpy(&recordBuffer[recorded], pdmBuffer, toCopy * sizeof(short));
//             pdmSamplesReady = 0;
//             interrupts();
//             recorded += toCopy;
//         }
//     }
    
//     // Print as CSV for Python to read
//     Serial.println("BEGIN_PCM");
//     for (int i = 0; i < 16000; i++) {
//         Serial.println(recordBuffer[i]);
//     }
//     Serial.println("END_PCM");
//     done = true;
// }